#!/usr/bin/env python3
"""
Build a standalone snocomm executable with PyInstaller.

Bundles the unified CLI plus all 77 corporate modules for offline use
(e.g. internal infrastructure security posture reviews).

Usage:
    pip install -e ".[executable]"
    python tools/build_executable.py
    python tools/build_executable.py --onefile --clean
"""

from __future__ import annotations

import argparse
import platform
import shutil
import stat
import subprocess
import sys
from pathlib import Path


def parse_manifest_packages(manifest_path: Path) -> list[str]:
    packages: list[str] = []
    for line in manifest_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("package_name:"):
            packages.append(stripped.split(":", 1)[1].strip())
    return packages


def collect_datas(root: Path) -> list[tuple[str, str]]:
    datas: list[tuple[str, str]] = []

    manifest = root / "corporate" / "manifest.yaml"
    if manifest.exists():
        datas.append((str(manifest), "corporate"))

    release_batches = root / "corporate" / "release_batches.yaml"
    if release_batches.exists():
        datas.append((str(release_batches), "corporate"))

    corporate = root / "corporate"
    for module_dir in sorted(corporate.iterdir()):
        if not module_dir.is_dir():
            continue
        src = module_dir / "src"
        if src.is_dir():
            datas.append((str(src), f"corporate/{module_dir.name}/src"))

    return datas


def collect_hidden_imports(root: Path) -> list[str]:
    packages = parse_manifest_packages(root / "corporate" / "manifest.yaml")
    hidden = [
        "snocomm",
        "snocomm.cli",
        "snocomm.manifest",
        "snocomm.loader",
        "snocomm.runner",
        "snocomm.posture",
        "snocomm.paths",
        "shared",
        "shared.pipeline",
        "click",
        "pydantic",
    ]
    for pkg in packages:
        hidden.append(f"{pkg}.core")
        hidden.append(f"{pkg}.models")
    return hidden


def platform_asset_name() -> str:
    """Default release filename: snocomm-{os}-{arch}[.exe]."""
    system = platform.system().lower()
    machine = platform.machine().lower()
    arch = "x86_64" if machine in {"amd64", "x86_64"} else machine
    if system == "windows":
        return f"snocomm-windows-{arch}.exe"
    if system == "darwin":
        return f"snocomm-darwin-{arch}"
    return f"snocomm-linux-{arch}"


def built_binary_path(root: Path, onefile: bool) -> Path:
    if onefile:
        name = "snocomm.exe" if platform.system() == "Windows" else "snocomm"
        return root / "dist" / name
    folder = root / "dist" / "snocomm"
    name = "snocomm.exe" if platform.system() == "Windows" else "snocomm"
    return folder / name


def write_spec(root: Path, onefile: bool) -> Path:
    datas = collect_datas(root)
    hidden = collect_hidden_imports(root)
    spec_path = root / "tools" / "snocomm.generated.spec"

    datas_repr = ",\n        ".join(repr(item) for item in datas)
    hidden_repr = ",\n        ".join(repr(item) for item in hidden)
    exe_mode = "True" if onefile else "False"

    spec_path.write_text(
        f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by tools/build_executable.py — do not edit manually.

block_cipher = None

a = Analysis(
    ['{root / "snocomm" / "__main__.py"}'],
    pathex=['{root}'],
    binaries=[],
    datas=[
        {datas_repr}
    ],
    hiddenimports=[
        {hidden_repr}
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='snocomm',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

if not {exe_mode}:
    coll = COLLECT(
        exe,
        a.binaries,
        a.zipfiles,
        a.datas,
        strip=False,
        upx=True,
        upx_exclude=[],
        name='snocomm',
    )
""",
        encoding="utf-8",
    )
    return spec_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Build standalone snocomm executable")
    parser.add_argument("--onefile", action="store_true", help="Single-file executable (default)")
    parser.add_argument("--onedir", action="store_true", help="Directory distribution")
    parser.add_argument("--clean", action="store_true", help="Clean PyInstaller cache before build")
    parser.add_argument(
        "--rename",
        metavar="NAME",
        help="Copia el binario a dist/NAME (default: snocomm-{os}-{arch})",
    )
    args = parser.parse_args()

    onefile = not args.onedir
    root = Path(__file__).resolve().parents[1]

    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print("Install PyInstaller: pip install -e '.[executable]'", file=sys.stderr)
        return 1

    spec_path = write_spec(root, onefile=onefile)
    cmd = [sys.executable, "-m", "PyInstaller", str(spec_path), "--noconfirm"]
    if args.clean:
        cmd.append("--clean")

    print(f"Building snocomm for {platform.system()} ({platform.machine()})...")
    print(f"Mode: {'onefile' if onefile else 'onedir'}")
    result = subprocess.run(cmd, cwd=root)
    if result.returncode != 0:
        return result.returncode

    binary = built_binary_path(root, onefile=onefile)
    if not binary.exists():
        print("Build finished but binary path not found — check dist/", file=sys.stderr)
        return 1

    release_name = args.rename or platform_asset_name()
    release_path = root / "dist" / release_name
    if release_path != binary:
        shutil.copy2(binary, release_path)

    if platform.system() != "Windows":
        mode = release_path.stat().st_mode
        release_path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    size_mb = release_path.stat().st_size / (1024 * 1024)
    print(f"\n✅ Executable: {release_path} ({size_mb:.1f} MiB)")
    print("\nSmoke test:")
    subprocess.run([str(release_path), "--version"], check=False)
    print(f"\nInfrastructure posture review:\n  {release_path} posture --json")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())